language: python
python:
  - 3.3
  - 2.7
env:
  - ADDITIONAL_REQUIREMENTS='git+https://github.com/django/django.git@stable/1.7.x'
  - ADDITIONAL_REQUIREMENTS='django>=1.6,<1.7 south>=0.8'
  - ADDITIONAL_REQUIREMENTS='django>=1.6,<1.7'  
  - ADDITIONAL_REQUIREMENTS='django>=1.5,<1.6 south>=0.8'
  - ADDITIONAL_REQUIREMENTS='django>=1.5,<1.6'
addons:
  postgresql: 9.2
branches:
  except:
    - /-unstable$/
cache: apt
install:
  # Install pip requirements.
  - pip install --upgrade setuptools pip
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  - pip install $ADDITIONAL_REQUIREMENTS
  - pip install coverage coveralls

  # Create our database.
  - psql -U postgres -c 'create database django_pg;'
  - psql -U postgres -d django_pg -c 'create extension postgis;'
script:
  - coverage run -p tests/runtests.py
  - coverage run -p tests/runtests.py gis
after_success:
  - coveralls
